### ISSUE TITLE
The type initializer for 'SkiaSharp.SKImageInfo' threw an exception

### ISSUE THREAD

**Issue by sdagkas** [tossnet/Blazor-Captcha#11]
Using BlazorCaptcha 1.2.4 in a .NET 6 project results in the following runtime error:

Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: The type initializer for 'SkiaSharp.SKImageInfo' threw an exception.
System.TypeInitializationException: The type initializer for 'SkiaSharp.SKImageInfo' threw an exception.
 ---> System.DllNotFoundException: libSkiaSharp
   at SkiaSharp.SKImageInfo..cctor()
   --- End of inner exception stack trace ---
   at BlazorCaptcha.Captcha.BuildRenderTree(RenderTreeBuilder builder)
   at Microsoft.AspNetCore.Components.ComponentBase.<.ctor>b__6_0(RenderTreeBuilder builder)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment, Exception& renderFragmentException)

**Comment by crippledfaith** [comment]
Same here, added SkiaSharp, SkiaSharp.NativeAssets.WebAssembly, still not working

**Comment by a-bagherian** [comment]
**blazor wasm**

Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: The type initializer for 'SkiaSharp.SKImageInfo' threw an exception.
System.TypeInitializationException: The type initializer for 'SkiaSharp.SKImageInfo' threw an exception.
 ---> System.DllNotFoundException: libSkiaSharp
   at SkiaSharp.SKImageInfo..cctor()
   --- End of inner exception stack trace ---
   at BlazorCaptcha.Captcha.BuildRenderTree(RenderTreeBuilder builder)

**Comment by nlpsl202** [comment]
same here
I am using wasm

Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: The type initializer for 'SkiaSharp.SKImageInfo' threw an exception.
System.TypeInitializationException: The type initializer for 'SkiaSharp.SKImageInfo' threw an exception.
 ---> System.DllNotFoundException: libSkiaSharp
   at SkiaSharp.SKImageInfo..cctor()
   --- End of inner exception stack trace ---
   at BlazorCaptcha.Captcha.BuildRenderTree(RenderTreeBuilder builder) in D:\VSO\Blazor-Captcha\BlazorCaptcha\Captcha.cs:line 105
   at Microsoft.AspNetCore.Components.ComponentBase.<.ctor>b__6_0(RenderTreeBuilder builder)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment, Exception& renderFragmentException)

**Comment by elshorbagy** [comment]
I'm having the same problem.

**Comment by tossnet** [comment]
let's hope the SkiaSharp team finds a solution https://github.com/mono/SkiaSharp/issues/2732

**Comment by nickfortyau** [comment]
Works great in a non-docker environment, as soon as I deployed in AWS ECS in a docker image, I get this error

**Comment by tossnet** [comment]
I'll compile version 3.0.0 with the latest version of SkiaSharp, 3.119.2, and I won't have the Wasm 'SkiaSharp.SKImageInfo' threw an exception. error. 🤞
